name: ci

on: [push]

jobs:
  php:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php_version: ['8.1', '8.2']

    steps:
    - uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php_version }}

    - name: Cache Composer dependencies
      id: composer-cache
      run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

    - uses: actions/cache@v4
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: ${{ runner.os }}-composer-

    - name: Check Composer lock file is up to date
      run: composer validate --no-check-all

    - name: Install Composer dependencies
      run: composer install --no-progress --prefer-dist --optimize-autoloader

    - uses: actions/cache@v4
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ hashFiles('**/web/app/themes/*/composer.lock') }}
        restore-keys: ${{ runner.os }}-composer-

    - name: Check Composer lock file is up to date
      working-directory: web/app/themes/asmm
      run: composer validate --no-check-all

    - name: Install Composer dependencies
      working-directory: web/app/themes/asmm
      run: composer install --no-progress --prefer-dist --optimize-autoloader

    - name: Run tests
      working-directory: web/app/themes/asmm
      run: composer style:check
