name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        path: bedrock

    - uses: actions/setup-node@v2
      with:
        node-version: '16'
        cache: yarn
        cache-dependency-path: bedrock/web/app/themes/asmm/yarn.lock

    - uses: actions/checkout@v2
      with:
        repository: codepuncher/asmm-trellis
        path: trellis
        token: ${{ secrets.REPO_PAT }}

    - uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.TRELLIS_DEPLOY_SSH_PRIVATE_KEY }}
        known_hosts: ${{ secrets.TRELLIS_DEPLOY_SSH_KNOWN_HOSTS }}

    - uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.TRELLIS_DEPLOY_SSH_PRIVATE_KEY }}

    - uses: roots/setup-trellis-cli@v1
      with:
        ansible-vault-password: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}

    - name: Deploy
      run: trellis deploy production
      working-directory: trellis
